---
title: "Task 1 Write Up"
author: "Imar Colic"
date: "2024-12-08"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Task 1: Binary Classification

## Abstract Task 1

-   abstract/overview of task

## Task 1.1 Data Description

-   summary statistics
-   plots

## Task 1.2 Summary Table without PCA

-   short intro (1-2 sentences what every classifier does)
-   after showing summary table, add explanation to specific occurances like the QDA or kNN or SVM

| w/o PCA             | Accuracy   | Bal. Accuracy | AUC                           | F1         |
|---------------|---------------|---------------|---------------|---------------|
| LDA                 |            |               |                               |            |
| Logistic            |            |               |                               |            |
| QDA                 | N/A        | N/A           | N/A                           | N/A        |
| k-NN                | 0.7424658  | 0.6963545     | 0.6963545 (not smooth curve)  | 0.5982906  |
| GDBT                |            |               |                               |            |
| RF                  |            |               |                               |            |
| SVM (Linear Kernel) | 0.95525114 | 0.94792398    | 0.94792398 (not smooth curve) | 0.93943140 |

## Task 1.2 Summary Table with PCA

-   explanation of what PCA does and how it is essentially applied for all classifiers

| with PCA            | Accuracy   | Bal. Accuracy | AUC        | F1         |
|---------------------|------------|---------------|------------|------------|
| LDA                 |            |               |            |            |
| Logistic            |            |               |            |            |
| QDA                 | 0.94063927 | 0.93002086    | 0.98742614 | 0.91864831 |
| k-NN                | 0.91141553 | 0.83837707    | 0.88995297 | 0.87253614 |
| GDBT                |            |               |            |            |
| RF                  |            |               |            |            |
| SVM (Linear Kernel) | 0.94885845 | 0.94183745    | 0.94792398 | 0.93103448 |
| SVM (Radial Kernel) | 0.94977169 | 0.94020409    | 0.94020409 | 0.93133583 |

## Task 1.3 Improved Classifiers

-   Summary Table: of F1 before and F1 after improvement

|                       | F1 Score before | F1 Score after |
|-----------------------|-----------------|----------------|
| QDA/LDA??             |                 |                |
| Logistic (with Ridge) |                 |                |
| RF (with AdaBoost)    |                 |                |

-   explanation how each classifier was improved and why this improvement method was chosen

## Task 1.4 Final predict function

-   summary and discussion of the results

|             | Accuracy | Bal. Accuracy | AUC | F1 Score |
|-------------|----------|---------------|-----|----------|
| mypredict() |          |               |     |          |

-   present in one row all performance metrics of chosen prediction function
